### Login 
POST {{host}}auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "anees",
    "password": "password123"
}



### Me 
GET {{host}}auth/me HTTP/1.1
Content-Type: application/json
authorization: {{token}}